### ISSUE TITLE
Please add attribution and license

### ISSUE THREAD

**Issue by M4xi1m3** [nwagyu/periodic#1]
This seems to come from [here](https://github.com/Omega-Numworks/Omega-External/blob/master/apps/Periodic/periodic.c), which is a port of my old [periodic table](https://github.com/M4xi1m3/nw-atom), which was made by Zardam.
I would like you to add the CC BY-NC-SA license to this repository, and add attribution to Zardam and myself.
Best regards.

**Comment by ScarlettSpell** [comment]
Fixed in 3ff3298d
